version: "3.3"
services:
  

  uatapiebidding.epg.co.th:
    extends:
      file: ./extends-compose/uatapiebidding.epg.co.th.yml
      service: uatapiebidding.epg.co.th
    env_file:
      - ./uatapiebidding.epg.co.th/.env
    networks:
            my_network:
                ipv4_address: 172.15.0.7
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/16

